export const SET_SELECTED_COUNTRY = 'SET_SELECTED_COUNTRY';
export const COUNTRIES_HAVE_ERROR = 'COUNTRIES_HAVE_ERROR';
export const COUNTRIES_ARE_LOADING = 'COUNTRIES_ARE_LOADING';
export const COUNTRIES_FETCH_SUCCESS = 'COUNTRIES_FETCH_SUCCESS';